### PR TITLE
Fix category selection from autocomplete

### LINKED ISSUE #582: Clicking on a search suggestion crashes the frontend app
## Bug Report

**Expected behavior/code**

When clicking on a search suggestion, we expect to filter the search given clicked suggestion.

**Actual Behavior**

The frontend app crashes and a blank screen shows.

**Steps to Reproduce**

1. Go to the courses page, _e.g._ https://richie.education/fr/cours/
2. Type `arti`, click on the "Adaptive bandwidth-monitored artificial intelligence" suggestion
3. :boom: the frontend app just crashed

**Environment**

- Richie version: at least from `7051ab0` and probably before
- Platform: all

**Additional context/Screenshots**

richie-text-search-fail

### PR DESCRIPTION
**Pull request by mbenadda**
## Purpose

Selecting a category in the autocomplete suggestions caused the app to crash. This was due to a mismatch between the filters object, that contained definitions for meta-categories, and the autocomplete code, which was looking for a "category" definition.

## Proposal

This can be fixed by adding the path to filter definitions and searching in the filters object for a definition that matches the beginning of the filter we're attempting to add.

Closes #582

### CODE REVIEW

File: src/frontend/js/types/filters.ts [hunk 1]
```diff
@@ -1,10 +1,13 @@
+import { Nullable } from '../utils/types';
+
 export interface FilterValue {
   count: number;
   human_name: string;
   key: string;
 }
 
 export interface FilterDefinition {
+  base_path: Nullable<string>;
```
Comment (lunika) [inline src/frontend/js/types/filters.ts]: you can maybe add a comment explaining what is this `base_path` ?
