### PR TITLE
🐛(frontend) fix syllabus "Go to course" link

### LINKED ISSUE #2267: Joanie Coure Run enrollment resource link
## Bug Report

**Problematic Behavior**
When a course run is managed by Joanie if the user is enrolled to a Course Run the link "Go to course" is not set properly. Indeed, the link targets the joanie course run endpoint instead of the lms course page.

**Expected behavior/code**
The "Go to course" button should targets the lms page (this information is returned by Joanie into the enrollment information).

**Steps to Reproduce**
1. Go to a syllabus page with an opened course run managed by Joanie
2. Enroll to this course run
3. Click on the "Go to course" button

**Environment**
- Richie version: 2.25.0-beta.1
- Platform: Preprod

**Additional context/Screenshots**
image

### PR DESCRIPTION
**Pull request by rlecellier**
When a course run is managed by Joanie if the user is enrolled to a Course Run the link "Go to course" is not set properly. Indeed, the link targets the joanie course run endpoint instead of the lms course page.

resolve #2267

### CODE REVIEW

File: src/frontend/js/types/Joanie.ts [hunk 1]
```diff
@@ -192,6 +192,21 @@ export interface Enrollment {
   product_relations: CourseProductRelation[];
   certificate_id?: string;
 }
+export const isEnrollment = (obj: unknown | Enrollment | OpenEdXEnrollment): obj is Enrollment => {
```
Comment (jbpenrath) [inline src/frontend/js/types/Joanie.ts:195]: WDYT ?
```suggestion
export const isJoanieEnrollment = (obj: unknown | JoanieEnrollment | OpenEdXEnrollment): obj is Enrollment => {
```

File: src/frontend/js/utils/test/factories/joanie.ts [hunk 2]
```diff
@@ -81,6 +81,7 @@ export const EnrollmentFactory = factory((): Enrollment => {
     was_created_by_order: false,
     created_on: faker.date.past({ years: 1 }).toISOString(),
     orders: [],
+    certificate_id: faker.string.uuid(),
```
Comment (jbpenrath) [inline src/frontend/js/utils/test/factories/joanie.ts:84]: certificate_id is optional, from my point of view, by default the value should be `null`.

**Review by jbpenrath — APPROVED** [review]
