### PR TITLE
🚑(frontend) fix search query string formatting

### LINKED ISSUE #1673: Search crash when several languages are selected
## Bug Report

**Expected behavior/code**
A user should be able to search courses available in several languages

**Actual Behavior**
If user wants to filter with several languages, the search crash.

**Steps to Reproduce**
1. Go to the search page
2. In the sidebar, in the languages filter pane, select several languages
3. Boom, the search crash

**Environment**
- Richie version: 2.14.0
- Platform: Mac OS

**Possible Solution**
Investigate why elasticsearch returns a 400 Bad request in this case.

**Additional context/screenshots**
```json
{"errors":{"languages":["Select a valid choice. en,ar is not one of the available choices."]}}
```

### PR DESCRIPTION
**Pull request by jbpenrath**
## Purpose

The search filter query string was not formatted properly so when a user wanted to filter results with several languages the search request returned a 400 Bad Request error.

Resolve #1673

## Proposal

- [x] Remove `arrayFormat: 'comma'` option to the method to serialize search params into query string

### CODE REVIEW

File: src/frontend/js/data/getResourceList/index.ts [hunk 1]
```diff
@@ -17,14 +17,11 @@ export async function fetchList(
...
-      {
-        headers: {
-          'Content-Type': 'application/json',
-        },
+    const response = await fetch(`/api/v1.0/${kind}/?${stringify(params)}`, {
+      headers: {
+        'Content-Type': 'application/json',
       },
-    );
+    });
```
Comment (sampaccoud) [inline src/frontend/js/data/getResourceList/index.ts:24]: I'm curious, why didn't the linter catch it?

**Review by sampaccoud — APPROVED** [review]

File: src/frontend/js/data/getResourceList/index.ts (hunk 1 above)
Comment (jbpenrath) [reply src/frontend/js/data/getResourceList/index.ts:24]: Because, there was a comma before.
It acts like black linter with tuple in python
`('item1',)` is not formatted but `('item1')` is formatted into `'item1'`
